SELECT B.AUTHOR_ID,
       B.AUTHOR_NAME,
       A.CATEGORY,
       SUM(C.SALES * A.PRICE) AS TOTAL_SALES
FROM BOOK A JOIN AUTHOR B USING (AUTHOR_ID)
     JOIN BOOK_SALES C USING (BOOK_ID)
WHERE DATE_FORMAT(C.SALES_DATE,'%Y-%m') = '2022-01'
GROUP BY B.AUTHOR_ID, A.CATEGORY
ORDER BY B.AUTHOR_ID, A.CATEGORY DESC
