SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_OUTS A JOIN (SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
                         FROM ANIMAL_INS
                         WHERE SEX_UPON_INTAKE LIKE '%Intact%') B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_OUTCOME NOT LIKE '%Intact%'
ORDER BY A.ANIMAL_ID